version: '3.4'


services:
    ros_core:
        build:
            context: .
            dockerfile: dockerfiles/dev/harmoni-dev
            #network: host
        image: cmbirmingham/harmoni-dev:latest
        environment:
            DISPLAY: $DISPLAY
            QT_GRAPHICSSYSTEM: native
            ROS_DISTRO: kinetic
            ROS_MASTER_URI: $ROS_MASTER_URI
            IS_DOCKER_ENV: "true"
            CATKIN_WS: harmoni_catkin_ws
        privileged: true
        network_mode: host
        devices: 
          - /dev/dri:/dev/dri
          - /dev/snd:/dev/snd
          - /dev/video0:/dev/video0
        volumes:
          - harmoni_catkin_ws:/root/harmoni_catkin_ws
          # IDEs
          - pycharm_config:/root/.PyCharmCE2019.3/
          - aws_config:/root/.aws/
          - visual_code_config:/root/.visual_code/
          - ~/.vscode/:/root/.vscode/
          # Configuration
          - ./config/setup_script.sh:/root/.setup_script.sh
          - ./config/dev_setup_script.sh:/root/.dev_setup_script.sh
          # Other
            - ~/.config/terminator/config:/root/.config/terminator/config
            - ~/.gitconfig/:/root/.gitconfig/:ro
          - ~/.vimrc:/root/.vimrc:ro
          - ~/.vim/:/root/.vim/:ro
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        working_dir: /root/harmoni_catkin_ws/src/HARMONI
        command: bash -c "
            terminator -ue \"echo 'Entering ros_core Container...' &&
            bash\" &&
            source /root/harmoni_catkin_ws/devel/setup.bash &&
            roslaunch harmoni_decision test.launch test_service:="service_to_test""

    ros_w2l:
        build:
            context: .
            dockerfile: dockerfiles/ros-kinetic_harmoni_w2l-inf
            network: host
        image: harmoni/ros-kinetic_harmoni_w2l-inf:latest
        environment:
            DISPLAY: $DISPLAY
            QT_GRAPHICSSYSTEM: native
            ROS_DISTRO: kinetic
            IS_DOCKER_ENV: "true"
            CATKIN_WS: harmoni_catkin_ws
            ROS_MASTER_URI: $ROS_MASTER_URI
        privileged: true
        network_mode: host
        devices: 
            - /dev/dri:/dev/dri
            - /dev/snd:/dev/snd
            - /dev/video0:/dev/video0
        volumes:
            - harmoni_catkin_ws:/root/harmoni_catkin_ws
            - ~/coding/w2l/model/:/root/model/
            - wav2letter:/root/wav2letter
            # Configuration
            - ./config/setup_script.sh:/root/.setup_script.sh
            - ./config/dev_setup_script.sh:/root/.dev_setup_script.sh
            # Other
            - ~/.config/terminator/config:/root/.config/terminator/config
            - ~/.gitconfig/:/root/.gitconfig/:ro
            - ~/.vimrc:/root/.vimrc:ro
            - ~/.vim/:/root/.vim/:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        working_dir: /root/harmoni_catkin_ws/src/HARMONI
        command: bash -c "
            terminator -ue \"echo 'Entering ros_w2l Container...' &&
            bash\" &&
            source /root/harmoni_catkin_ws/devel/setup.bash"
    

volumes:
    harmoni_catkin_ws:
    wav2letter:
    aws_config:
    pycharm_config:
    visual_code_config:

# networks:
#     ros_net:
#         driver: bridge
#         ipam:
#             driver: default
#             config:
#             -   subnet: 172.19.0.0/24
#             #gateway: 172.19.0.1